### PR TITLE
Ship elementary-style icon

### PR DESCRIPTION
**Pull request by danirabbit**
Bundle the icon we currently ship in the icon theme with the Flatpak instead. Fixes having an incorrect icon in AppCenter

Same as https://github.com/elementary/evince/pull/24 for example

### CODE REVIEW

**Comment by locness3** [comment]
not sure that really looks like a browser icon

**Comment by locness3** [comment]
New one reminds me of the [Moka](https://snwh.org/moka) theme :

**Review by lenemter — APPROVED** [review]

**Comment by locness3** [comment]
So the new design was simply reverted?

**Comment by danirabbit** [comment]
@locness3 Ive got it in a different branch: #74

**Pull request merged**
