### PR TITLE
PostInst: bump GL version

### LINKED ISSUE #125: Nothing renders after latest update
### What Happened?

After running the latest batch of updates Web no longer renders pages. I get a completely blank page. It seems to be a graphical issue as the loading status seems normal and moving the mouse over the blank page does change the cursor and show hyperlinks in the status bar at the bottom of the window.

### Steps to Reproduce

I just ran all updates that were available at the time and ended up with Web 45.1 and no pages rendering on screen. AppCenter currently shows no updates pending.

### Expected Behavior

Before the updates pages were rendering fine and now they are not.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

I am running Elementary in a VM on proxmox using the basic default settings for bios, display, machine, with a virtio scsi controller and virtio network device. I am using 2 cores and 4GB of RAM. The CPU type is host and the underlying hardware is an intel mac mini with a 2.3Ghz core i7 cpu. I have been running elementary off and on since version 6 on this machine with relatively few issues with the supported feature set of Elementary.

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes #125

### CODE REVIEW

**Comment by danirabbit** [comment]
@alatiera for some reason we're having an issue where folks aren't getting the new runtime when they update and the repo has already been added.

I'm not sure if we're doing postinst instead of preinst here because of packagekit or something :thinking:

**Comment by meisenzahl** [comment]
@danirabbit I'm afraid that this approach won't work because we handle native updates as offline updates. So this update would fail because of a missing Internet connection.

**Comment by Marukesu** [comment]
@alatiera the problem is that flatpak won't install a runtime from a different repository automatically, so we need to install it manually.

> I'm afraid that this approach won't work because we handle native updates as offline updates. So this update would fail because of a missing Internet connection.

AFAIK, this package is used only for installing the flatpak during a fresh install, so a fail isn't a problem.

**Comment by danirabbit** [comment]
Yeah at the least we can spin a new ISO so that whoever downloads now won't encounter this issue

**Pull request merged**
