### PR TITLE
Update to GNOME Web 42

### PR DESCRIPTION
**Pull request by cassidyjames**
- [x] Update LibDazzle to latest release
- [x] Update LibPortal dep to match upstream
- [x] Remove dark style patch as it's upstream
- [x] Revisit navigation buttons patch
- [x] Revisit tab close position patch
- [x] Fix the styling https://github.com/elementary/stylesheet/pull/1201

Depends on:
- [x] https://github.com/elementary/flatpak-platform/pull/93

### CODE REVIEW

**Comment by davidmhewitt** [comment]
The navigation buttons patch applies cleanly, the other was upstreamed, so I removed it.

Build fails due to missing `libhandy >= 1.5.0` in our runtime. We have 1.4.0

**Comment by alatiera** [comment]
Till then you could bundle libhandy inside the app and it should work fine.

**Comment by davidmhewitt** [comment]
Seeing some differences in the headerbar padding with our stylesheet.

Screenshot from 2022-03-23 14 12 43

Screenshot from 2022-03-23 14 13 02

**Comment by mcatanzaro** [comment]
Heads-up: this will be the final release using GTK 3. Please plan accordingly.

**Comment by cassidyjames** [comment]
It appears I don't have permission to edit this PR, but note that 42.1 and 42.2 have been released with regression and CVE fixes, so you'll want to be sure to bump that in the manifest. https://gitlab.gnome.org/GNOME/epiphany/-/tags/42.2

**Review by danrabbit — APPROVED** [review]
Confirmed this looks good on OS 6 and 7 :rocket:

**Pull request merged**
