### PR TITLE
Read Granite.Settings.prefers_color_scheme

### LINKED ISSUE #11: Epiphany does not use dark style (Whether set globally or in the settings itself)
## What Happened
Latest daily build of eOS 6 I set the global theme to dark and it looks amazing (By teh way) I launch Epiphany and the header bars, etc are all still light themed. I entered the settings and noticed under appearance it was set to the light theme. I changed that there as well and yet it all still remains light

## Expected Behavior
For header bars to honour tey global appearance limits, or at minimum for the headers to go dark when seledcted

## Steps to Reproduce
Launch Epiphany - lol

### Logs
Nothing that I can think of, however will gladly supply logs if you can let me know how to run it for that.

## Platform Information
elementaryos-6.0-daily.20210422

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #11 

Screenshot from 2021-05-20 11 35 33

### CODE REVIEW

**Review by cassidyjames — APPROVED** [review]
lfg dark style

**Comment by brodock** [comment]
how long until we can see that on the testing image? (I was expecting that after more than 24 hours the new browser would be updatable. Is there anything missing on the flatpak side to generate a new build?

**Comment by Marukesu** [comment]
@brodock the flatpak branch was changed, you need to install the daily branch with `flatpak install appcenter org.gnome.Epiphany//daily` and remove the old branch with `flatpak remove org.gnome.Epiphany//master`

**Comment by brodock** [comment]
@Marukesu thanks, that worked. I'm curious about how does Elementary plan to make this kind of change "reflected" as part of a regular installation? Will those changes be triggered by a script in a debian package? Or is the plan to have all default flatpak packages having a single parent dependency?

**Pull request merged**
